import { Person } from './types';

export const PEOPLE: Readonly<Record<string, Person>> = {
  rachelCarson: {
    name: 'Rachel Carson',
    context: `
    Born and raised in Springdale, Pennsylvania, near Pittsburgh, Carson witnessed how coal mining was despoiling the rural setting she loved. Already a devoted writer, the young Carson published several stories in the children’s magazine St. Nicholas. At Pennsylvania College for Women (now Chatham University), where she had been recruited as a scholarship student for her proven writing ability, she changed her major to biology—to the chagrin of some faculty members.

    After graduation she held a summertime study fellowship at the Marine Biological Laboratory at Woods Hole, Massachusetts. There she first experienced the ocean environment, which later became the topic of several of her best-selling books. She then entered Johns Hopkins University and completed a master’s degree in marine zoology while serving as a teaching assistant and part-time instructor in biology at Johns Hopkins and the University of Maryland. When her father died, Carson became the sole support of her mother, who soon after had to raise two grandchildren when her other daughter died in 1937.`
  },
  katherineJohnson: {
    name: 'Katherine Johnson',
    context: `Katherine Johnson was an American mathematician whose calculations of orbital mechanics as a NASA employee were critical to the success of the first and subsequent US crewed spaceflights. During her 33-year career at NASA and its predecessor, she earned a reputation for mastering complex manual calculations and helped pioneer the use of computers to perform the tasks. The space agency noted her "historical role as one of the first African-American women to work as a NASA scientist."`
  },
  sunTzu: {
    name: 'Sun Tzu',
    context: `Sun Tzu was a Chinese military general, strategist, philosopher, and writer who lived during the Eastern Zhou period of 771 to 256 BCE. Sun Tzu is traditionally credited as the author of The Art of War, an influential work of military strategy that has affected both Western and East Asian philosophy and military thinking. Sun Tzu is revered in Chinese and East Asian culture as a legendary historical and military figure. His birth name was Sun Wu (traditional Chinese: 孫武; simplified Chinese: 孙武) and he was known outside of his family by his courtesy name Changqing (Chinese: 長卿).[citation needed] The name Sun Tzu by which he is more popularly known is an honorific which means "Master Sun".

    Sun Tzu's historicity is uncertain. The Han dynasty historian Sima Qian and other traditional Chinese historians placed him as a minister to King Helü of Wu and dated his lifetime to 544–496 BCE. Modern scholars accepting his historicity place the extant text of The Art of War in the later Warring States period of 475 to 221 BCE – based on its style of composition and its descriptions of warfare. Traditional accounts state that the general's descendant Sun Bin wrote a treatise on military tactics, also titled The Art of War. Since both Sun Wu and Sun Bin were referred to as "Sun Tzu" in classical Chinese texts, some historians believed them identical, prior to the rediscovery of Sun Bin's treatise in 1972.
    
    Sun Tzu's work has been praised and employed in East Asian warfare since its composition. During the twentieth century, The Art of War grew in popularity and saw practical use in the Western world as well. It remains influential in many contemporary competitive endeavors across the modern world beyond military strategy and warfare, including espionage, culture, politics, business, and sports.`
  },
  gottfriedLeibniz: {
    name: 'Gottfried Wilhelm Leibniz',
    context: `Gottfried Wilhelm (von) Leibniz (1 July 1646 [O.S. 21 June] – 14 November 1716) was a German polymath active as a mathematician, philosopher, scientist and diplomat. He is one of the most prominent figures in both the history of philosophy and the history of mathematics. He wrote works on philosophy, theology, ethics, politics, law, history and philology. Leibniz also made major contributions to physics and technology, and anticipated notions that surfaced much later in probability theory, biology, medicine, geology, psychology, linguistics and computer science. In addition, he contributed to the field of library science: while serving as overseer of the Wolfenbüttel library in Germany, he devised a cataloging system that would have served as a guide for many of Europe's largest libraries. Leibniz's contributions to this vast array of subjects were scattered in various learned journals, in tens of thousands of letters and in unpublished manuscripts. He wrote in several languages, primarily in Latin, French and German, but also in English, Italian and Dutch.

    As a philosopher, he was one of the greatest representatives of 17th-century rationalism and idealism. As a mathematician, his greatest achievement was the development of the main ideas of differential and integral calculus, independently of Isaac Newton's contemporaneous developments, and mathematicians have consistently favored Leibniz's notation as the conventional and more exact expression of calculus.
    
    However, it was only in the 20th century that Leibniz's law of continuity and transcendental law of homogeneity found a consistent mathematical formulation by means of non-standard analysis. He was also a pioneer in the field of mechanical calculators. While working on adding automatic multiplication and division to Pascal's calculator, he was the first to describe a pinwheel calculator in 1685 and invented the Leibniz wheel, used in the arithmometer, the first mass-produced mechanical calculator. He also refined the binary number system, which is the foundation of nearly all digital (electronic, solid-state, discrete logic) computers, including the Von Neumann architecture, which is the standard design paradigm, or "computer architecture", followed from the second half of the 20th century, and into the 21st. Leibniz has been called the "founder of computer science".
    
    In philosophy and theology, Leibniz is most noted for his optimism, i.e. his conclusion that our world is, in a qualified sense, the best possible world that God could have created, a view sometimes lampooned by other thinkers, such as Voltaire in his satirical novella Candide. Leibniz, along with René Descartes and Baruch Spinoza, was one of the three great early modern rationalists. His philosophy also assimilates elements of the scholastic tradition, notably the assumption that some substantive knowledge of reality can be achieved by reasoning from first principles or prior definitions. The work of Leibniz anticipated modern logic and still influences contemporary analytic philosophy, such as its adopted use of the term "possible world" to define modal notions.`
  },
  gusteau: {
    name: 'Gusteau',
    context: `Auguste Gusteau is the posthumous overarching protagonist in the Disney•Pixar's 2007 animated feature film, Ratatouille. He was an acclaimed chef and the owner of Gusteau's, a five-star restaurant in Paris, France. After losing one of his stars to a scathing review by food critic Anton Ego, Gusteau died of a broken heart. An imaginary version of the chef endured in the mind of Remy, an aspiring rat chef for whom Gusteau was an inspiration.
    
    He is a renowned and extremely talented chef who wrote the bestseller Anyone Can Cook and founded the restaurant Gusteau's, which merited five stars. His personal motto is that "anyone can cook", and is prone to producing recipes with unusual flairs. He was the youngest chef in history to obtain a five-star restaurant, and was among one of the finest chefs worldwide.

After France's top food critic Anton Ego gave his restaurant an insulting review which led to the loss of one star rating from the restaurant, the review broke Gusteau's heart and he died shortly afterwards, which, according to tradition, resulted in the loss of another rating, meriting the restaurant three stars. Gusteau's ownership of the restaurant was handed over to his sous chef Skinner, who was not exactly faithful to his boss's ideals. He later appears as Remy's guide, leading him to Gusteau's.

It is later revealed that Alfredo Linguini is really the son of Gusteau. He is the son of Renata Linguini, with whom Gusteau once shared a romantic relationship. Linguini later acquires the restaurant after Remy informs him of this discovery and the demeaning cheap frozen food line Skinner had, that was exploiting the late Chef's likeness was halted.

Unfortunately, Skinner tries to sabotage Linguini's attempts to please returning customer Anton Ego by kidnapping Remy. Remy talks to Gusteau in his cage and is frustrated because he feels that all this time he has been pretending to be things he is not, like a rat for his dad and a human for Linguini, and that he (Gusteau) is really there for him to talk to. In his final appearance to Remy, Gusteau tells Remy that he doesn't need to pretend, and that he never did. He was being his true self the whole time. Uplifted by these words, Remy is freed and rushes to Linguini's aid, and the two succeed in impressing Ego and start a new partnership in which they remain respected chefs.

Gusteau does not appear again after Remy's kidnapping. Despite the eventual closing of his restaurant due to a rat infestation; however, his legacy lives on in Linguini and Remy, as they continue to cook astounding meals in a new restaurant appropriately named La Ratatouille.`
  }
} as const;
